import type { Metadata } from "next";
import { Instrument_Sans, Open_Sans } from "next/font/google";
import "./globals.css";
import MobileMenu from "./layout/Mobile_Header";
import Header from "./layout/Header";
import Footer from "./layout/Footer";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${openSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MobileMenu />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
